<a href="https://colab.research.google.com/github/saurabhmandaokar1999/GoogleColab/blob/main/Dealing_MissingValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
ls

'AB_NYC_2019 (1).csv'   sample_data/

In [4]:
df = pd.read_csv("AB_NYC_2019 (1).csv")

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,19-10-2018,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,21-05-2019,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,05-07-2019,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,19-11-2018,0.10,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36351,28917395,Ultra Plush Large Private cozy cottage Bedroom,217332035,Rose,Brooklyn,Sheepshead Bay,40.59055,-73.94640,Private room,39.0,1.0,1.0,31-10-2018,0.12,2.0,360.0
36352,28917505,Small room for 1 Person-Best Value,35927005,Kathy,Brooklyn,Borough Park,40.63448,-74.00563,Private room,50.0,1.0,2.0,20-06-2019,0.24,10.0,365.0
36353,28917781,Walk in Basement Room with Window,35927005,Kathy,Brooklyn,Borough Park,40.63586,-74.00597,Private room,55.0,1.0,1.0,20-10-2018,0.11,10.0,298.0
36354,28918134,Basement Room with Window,35927005,Kathy,Brooklyn,Borough Park,40.63525,-74.00724,Private room,48.0,1.0,0.0,NaN,NaN,10.0,365.0
36355,28918211,B1. Shared room for 4 guests,215588687,Levi,Brooklyn,Prospect-Lefferts Gar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,19-10-2018,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,21-05-2019,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,05-07-2019,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,19-11-2018,0.10,1.0,0.0

In [7]:
df.isna()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36351,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36352,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36353,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36354,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
36355,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True

In [8]:
df.isna().sum()

id                                   0
name                                16
host_id                              0
host_name                           20
neighbourhood_group                  0
neighbourhood                        0
latitude                             1
longitude                            1
room_type                            1
price                                1
minimum_nights                       1
number_of_reviews                    1
last_review                       5804
reviews_per_month                 5804
calculated_host_listings_count       1
availability_365                     1
dtype: int64

#Deleting Row With missing data

In [9]:
df2 = df.copy()

In [11]:
df2.dropna(inplace = True)

In [13]:
df2.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [15]:
df2.shape

(30530, 16)